mod count_largest_group;
pub mod count_partitions;
mod earliest_time;
mod find_lucky;
mod max_freq_sum;
pub mod max_width_of_vertical_area;
mod min_bitwise_array;
mod min_costs;
pub mod min_operations;
mod recover_order;
mod restore_string;
mod reverse_degree;
mod string_matching;
mod subarray_sum;
mod subset_xor_sum;

pub mod map_word_weights;

pub mod mirror_distance;
mod get_concatenation;
mod shuffle;
mod find_max_consecutive_ones;
mod find_error_nums;
mod smaller_numbers_than_current;
mod find_disappeared_numbers;
mod count_digit_occurrences;
mod minimized_string_length;
mod min_bit_flips;
mod left_right_difference;
mod min_moves_to_seat;
mod largest_local;
mod count_key_changes;
mod sum_of_the_digits_of_harshad_number;
mod gcd_of_odd_even_sums;
mod remove_trailing_zeros;
mod is_acronym;
mod cells_in_range;
mod final_string;
